name: Build and Release Windows ZIP

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller matplotlib

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --add-data "assets;assets" --add-data "data;data" game.py

      - name: Package into ZIP
        run: |
            mkdir release
            copy dist\game.exe release\
            xcopy /E /I /Y assets release\assets\
            xcopy /E /I /Y data release\data\
            powershell Compress-Archive -Path release\* -DestinationPath game-win.zip


      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Windows Build"
          files: game-win.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
